language: node_js
node_js:
- 6.11.1
sudo: false
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm config set spin false
- npm i -g npm@^5.3.0
install:
- npm --version
- npm install
script:
- npm test
notifications:
  email: false
